# Generated by Django 3.1.2 on 2021-06-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeoName', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSFunUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('gcsu_username', models.CharField(max_length=32, null=True, unique=True)),
                ('geocity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GeoName.geocity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'gpsfunuser',
            },
        ),
    ]
