# Generated by Django 3.1.2 on 2020-11-14 12:10

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_gpsfunuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsfunuser',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
