# Generated by Django 3.1.2 on 2020-11-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_gpsfunuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsfunuser',
            name='location',
        ),
    ]
