UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE oblast in ('Авт. респ.Крым','Севастополь','Симферопольская');
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE oblast in ('Алтайский край','Республика Алтай');
UPDATE geocacher SET admin_code='06', country_iso3='RUS' WHERE oblast='Архангельская';
UPDATE geocacher SET admin_code='06', country_iso3='RUS' WHERE oblast='Архангельская обл.';
UPDATE geocacher SET admin_code='06', country_iso3='KAZ' WHERE oblast='Атырауская обл.';
UPDATE geocacher SET admin_code='08', country_iso3='RUS' WHERE oblast in ('Башкортостан респ.','республика башкортостан', 'Башкортостан республика');
UPDATE geocacher SET admin_code='09', country_iso3='RUS' WHERE oblast='Белгородская';
UPDATE geocacher SET admin_code='09', country_iso3='RUS' WHERE oblast='Белгородская обл.';
UPDATE geocacher SET admin_code='10', country_iso3='RUS' WHERE oblast='Брянская обл.';
UPDATE geocacher SET admin_code='23', country_iso3='UKR' WHERE oblast='Винницкая обл.';
UPDATE geocacher SET admin_code='83', country_iso3='RUS' WHERE oblast='Владимирская обл.';
UPDATE geocacher SET admin_code='84', country_iso3='RUS' WHERE oblast='Волгоградская обл.';
UPDATE geocacher SET admin_code='85', country_iso3='RUS' WHERE oblast='Вологодская обл.';
UPDATE geocacher SET admin_code='24', country_iso3='UKR' WHERE oblast='Волынская обл.';
UPDATE geocacher SET admin_code='86', country_iso3='RUS' WHERE oblast='Воронежская обл.';
UPDATE geocacher SET admin_code='86', country_iso3='RUS' WHERE oblast='Воронежская область';
UPDATE geocacher SET admin_code='04', country_iso3='UKR' WHERE oblast='Днепропетровская';
UPDATE geocacher SET admin_code='04', country_iso3='UKR' WHERE oblast='Днепропетровская обл.';
UPDATE geocacher SET admin_code='05', country_iso3='UKR' WHERE oblast='Донецкая';
UPDATE geocacher SET admin_code='05', country_iso3='UKR' WHERE oblast='Донецкая обл.';
UPDATE geocacher SET admin_code='14', country_iso3='RUS' WHERE oblast in ('Забайкальский край','Читинская');
UPDATE geocacher SET admin_code='26', country_iso3='UKR' WHERE oblast='Запорожская обл.';
UPDATE geocacher SET admin_code='21', country_iso3='RUS' WHERE oblast='Ивановская обл.';
UPDATE geocacher SET admin_code='20', country_iso3='RUS' WHERE oblast='Иркутская обл.';
UPDATE geocacher SET admin_code='23', country_iso3='RUS' WHERE oblast='Калининградская обл.';
UPDATE geocacher SET admin_code='25', country_iso3='RUS' WHERE oblast='Калужская обл.';
UPDATE geocacher SET admin_code='28', country_iso3='RUS' WHERE oblast='Карелия респ.';
UPDATE geocacher SET admin_code='13', country_iso3='UKR' WHERE oblast='Киевская';
UPDATE geocacher SET admin_code='13', country_iso3='UKR' WHERE oblast='Киевская обл.';
UPDATE geocacher SET admin_code='10', country_iso3='UKR' WHERE oblast='Кировоградская обл.';
UPDATE geocacher SET admin_code='33', country_iso3='RUS' WHERE oblast in ('Кировская обл.', 'Кировская область');
UPDATE geocacher SET admin_code='37', country_iso3='RUS' WHERE oblast='Костромская обл.';
UPDATE geocacher SET admin_code='38', country_iso3='RUS' WHERE oblast in ('Краснодарский край', 'Krasnodar Krai');
UPDATE geocacher SET admin_code='91', country_iso3='RUS' WHERE oblast in ('Красноярский край','Таймырский авт. окр.');
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE oblast in ('Крым', 'Крым респ. и Севастополь', 'Республика Крым');
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE oblast='Крым Авт. Респ.';
UPDATE geocacher SET admin_code='40', country_iso3='RUS' WHERE oblast='Курганская обл.';
UPDATE geocacher SET admin_code='41', country_iso3='RUS' WHERE oblast='Курская обл.';
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE oblast in ('Ленинградская обл.', 'СПб и Ленинградская обл.', 'Санкт-Петебург', 'Питер', 'город Санкт-Петербург');
UPDATE geocacher SET admin_code='43', country_iso3='RUS' WHERE oblast in ('Липецкая обл.','Липецк', 'липецкая усманский');
UPDATE geocacher SET admin_code='14', country_iso3='UKR' WHERE oblast in ('Луганская обл.','Луганская');
UPDATE geocacher SET admin_code='15', country_iso3='UKR' WHERE oblast='Львовская обл.';
UPDATE geocacher SET admin_code='09', country_iso3='KAZ' WHERE oblast='Мангистауская обл.';
UPDATE geocacher SET admin_code='45', country_iso3='RUS' WHERE oblast='Марий Эл респ.';
UPDATE geocacher SET admin_code='05', country_iso3='BLR' WHERE oblast in ('Минская обл.','Минск');
UPDATE geocacher SET admin_code='46', country_iso3='RUS' WHERE oblast='Мордовия респ.';
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE oblast='Моск';
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE oblast in ('Москва, Московская область','Москва','москвовская','московская облость', 'Москва и Московская обл.', 'Московская область');
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE oblast='Московская';
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE oblast='Московская обл.';
UPDATE geocacher SET admin_code='49', country_iso3='RUS' WHERE oblast in ('Мурманская обл.','Мурманская','Мурманская область');
UPDATE geocacher SET admin_code='51', country_iso3='RUS' WHERE oblast in ('Нижегородская обл.', 'Нижегородская', 'Нижегородская область');
UPDATE geocacher SET admin_code='52', country_iso3='RUS' WHERE oblast='Новгородская обл.';
UPDATE geocacher SET admin_code='53', country_iso3='RUS' WHERE oblast='Новосибирская обл.';
UPDATE geocacher SET admin_code='17', country_iso3='UKR' WHERE oblast in ('Одесская обл.','Одесская');
UPDATE geocacher SET admin_code='54', country_iso3='RUS' WHERE oblast in ('Омская обл.','Омская');
UPDATE geocacher SET admin_code='56', country_iso3='RUS' WHERE oblast='Орловская обл.';
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE oblast='Останкинский Район';
UPDATE geocacher SET admin_code='57', country_iso3='RUS' WHERE oblast in ('Пензенская обл.','Пензенская', 'Пенза');
UPDATE geocacher SET admin_code='90', country_iso3='RUS' WHERE oblast='Пермская';
UPDATE geocacher SET admin_code='90', country_iso3='RUS' WHERE oblast='Пермский край';
UPDATE geocacher SET admin_code='18', country_iso3='UKR' WHERE oblast in ('Полтавская обл.','Полтавская');
UPDATE geocacher SET admin_code='59', country_iso3='RUS' WHERE oblast='Приморский край';
UPDATE geocacher SET admin_code='60', country_iso3='RUS' WHERE oblast='Псковская обл.';
UPDATE geocacher SET admin_code='63', country_iso3='RUS' WHERE oblast='Республика Саха (Якутия)';
UPDATE geocacher SET admin_code='61', country_iso3='RUS' WHERE oblast in ('Ростовская обл.', 'Ростовская обл + Краснодарский кр.');
UPDATE geocacher SET admin_code='62', country_iso3='RUS' WHERE oblast in ('Рязанская обл.','Рязанская область');
UPDATE geocacher SET admin_code='65', country_iso3='RUS' WHERE oblast in ('Самарская обл.','Самарская', 'Самарская и Челябинская');
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE oblast='Санкт-Петербург';
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE oblast in ('Санкт-Петербург, Ленинградская область', 'Питер', 'С.-Петербург');
UPDATE geocacher SET admin_code='67', country_iso3='RUS' WHERE oblast='Саратовская обл.';
UPDATE geocacher SET admin_code='63', country_iso3='RUS' WHERE oblast='Саха (Якутия) респ.';
UPDATE geocacher SET admin_code='64', country_iso3='RUS' WHERE oblast='Сахалинская обл.';
UPDATE geocacher SET admin_code='71', country_iso3='RUS' WHERE oblast in ('Свердловская обл.','Свердловская', 'Свердловская область','Сверлдловская', 'Екатернбург', 'Екатернбург');
UPDATE geocacher SET admin_code='69', country_iso3='RUS' WHERE oblast='Смоленская обл.';
UPDATE geocacher SET admin_code='70', country_iso3='RUS' WHERE oblast in ('Ставропольский край','Ставропольский');
UPDATE geocacher SET admin_code='72', country_iso3='RUS' WHERE oblast='Тамбовская обл.';
UPDATE geocacher SET admin_code='73', country_iso3='RUS' WHERE oblast='Татарстан респ.';
UPDATE geocacher SET admin_code='77', country_iso3='RUS' WHERE oblast='Тверская обл.';
UPDATE geocacher SET admin_code='76', country_iso3='RUS' WHERE oblast='Тульская обл.';
UPDATE geocacher SET admin_code='78', country_iso3='RUS' WHERE oblast in ('Тюменская обл.','Тюменская', 'Тюменская область');
UPDATE geocacher SET admin_code='80', country_iso3='RUS' WHERE oblast in ('Удмуртская респ.', 'Удмуртская Республика');
UPDATE geocacher SET admin_code='81', country_iso3='RUS' WHERE oblast in ('Ульяновская обл.', 'Ульяновская область');
UPDATE geocacher SET admin_code='30', country_iso3='RUS' WHERE oblast='Хабаровский край';
UPDATE geocacher SET admin_code='07', country_iso3='UKR' WHERE oblast in ('Харьковская обл.','Харьковская');
UPDATE geocacher SET admin_code='01', country_iso3='EST' WHERE oblast='Харьюмаа';
UPDATE geocacher SET admin_code='08', country_iso3='UKR' WHERE oblast='Херсонская обл.';
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE oblast='Челябинская обл.';
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE oblast in ('Челябинская область','челябинская','челябинская обл,');
UPDATE geocacher SET admin_code='01', country_iso3='UKR' WHERE oblast='Черкасская обл.';
UPDATE geocacher SET admin_code='16', country_iso3='RUS' WHERE oblast='Чувашская респ.';
UPDATE geocacher SET admin_code='88', country_iso3='RUS' WHERE oblast in ('Ярославская обл.','ярославская');
UPDATE geocacher SET admin_code='07', country_iso3='LVA' WHERE oblast='Латгале';
UPDATE geocacher SET admin_code='17', country_iso3='LVA' WHERE oblast='Курземе';
UPDATE geocacher SET admin_code='12', country_iso3='LVA' WHERE oblast='Земгале';
UPDATE geocacher SET admin_code='01', country_iso3='LVA' WHERE oblast='Видземе';
UPDATE geocacher SET admin_code='85', country_iso3='CZE' WHERE oblast='Brno';
UPDATE geocacher SET admin_code='ENG', country_iso3='GBR' WHERE oblast='london';
UPDATE geocacher SET admin_code='09', country_iso3='AZE' WHERE oblast LIKE '%Баку%';
UPDATE geocacher SET admin_code='59', country_iso3='BGR' WHERE oblast='Stara Zagora';


UPDATE geocacher SET admin_code='13', country_iso3='UKR' WHERE town IN ('Kiev', 'Київ', 'Киев', 'г. Киев.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='05', country_iso3='UKR' WHERE town IN ('г.Донецк', 'Donetsk', 'Донецк') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='UKR' WHERE town IN ('Днепр', 'Dnepropetrovsk', 'г. Днепропетровск', 'Днепропетровск', 'Хутор Днепропетровск Екатеринославской губернии :)') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town LIKE 'Москва%%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE town LIKE '%%Петербург%%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE town IN ('СПб', 'St.Petersburg', 'S-Pb', 'С-Пб', 'Тихвин', 'Лен область', 'Питер', 'Пушкин', 'Ленинград', 'Между Питером и Харьковм') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='84', country_iso3='RUS' WHERE town ='Волгоград' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='71', country_iso3='RUS' WHERE (town LIKE 'Екатеринбург%%' OR town = 'Новоуральск') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='17', country_iso3='UKR' WHERE town ='Одесса' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='53', country_iso3='RUS' WHERE town ='Новосибирск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='54', country_iso3='RUS' WHERE town ='Омск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='61', country_iso3='RUS' WHERE town ='Белая Калитва' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='RUS' WHERE town ='Валдай' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE town LIKE '%%Севастополь%%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town IN ('Жуковский', 'Зеленоград', 'Мытищи', 'Фрязино', 'Москов') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='05', country_iso3='BLR' WHERE town ='Минск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='73', country_iso3='RUS' WHERE town in ('Kazan','Казань') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town IN ('Moscow', 'Кашира', 'Кашира-1', 'Клин', 'Химки', 'Красногорск', 'Лыткарино') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='34', country_iso3='RUS' WHERE town in ('Syktyvkar','Сыктывкар') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='68', country_iso3='RUS' WHERE town in ('Владикавказ', 'г.Владикавказ') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='86', country_iso3='RUS' WHERE town ='Воронеж' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='RUS' WHERE town in ('Выкса', 'Саров') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='18', country_iso3='UKR' WHERE town ='г. Полтава' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='03', country_iso3='UKR' WHERE town ='г. Черновцы' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='UKR' WHERE town ='г.Харьков' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='09', country_iso3='UKR' WHERE town ='г.Шепетовка' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='24', country_iso3='RUS' WHERE town ='г. Элиста' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE town in ('Горно-Алтайск','Турочак') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='27', country_iso3='UKR' WHERE town in ('Житмоир', 'Житомир', 'Коростышев') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='UKR' WHERE town ='Ивано-Франковск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='23', country_iso3='RUS' WHERE town LIKE 'Калининград%%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='25', country_iso3='RUS' WHERE (town LIKE 'Калуга%%' OR town LIKE 'Обнинск%%') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='29', country_iso3='RUS' WHERE town in ('Кемерово', 'новокузнецк') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='41', country_iso3='RUS' WHERE town ='Курск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='44', country_iso3='RUS' WHERE town ='Магадан' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='01', country_iso3='RUS' WHERE town ='Майкоп' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='32', country_iso3='RUS' WHERE town in ('Нижневартовск','Сургут') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='RUS' WHERE town ='Нижний Новгород' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='16', country_iso3='UKR' WHERE town ='Николаев' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='87', country_iso3='RUS' WHERE town in ('Новый Уренгой', 'Ноябрьск', 'Тарко-Сале') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='55', country_iso3='RUS' WHERE town in ('Оренбург', 'Орск') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE town in ('пгт. Гурзуф', 'Симферополь') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='57', country_iso3='RUS' WHERE town ='Пенза' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='90', country_iso3='RUS' WHERE town ='Пермь' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='61', country_iso3='RUS' WHERE town ='Ростов-на-Дону' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='88', country_iso3='RUS' WHERE town in ('Рыбинск','Ярославль') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE town ='с. Усть-Кокса' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='65', country_iso3='RUS' WHERE town ='Самара' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='67', country_iso3='RUS' WHERE town in ('Саратов','Энгельс') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='69', country_iso3='RUS' WHERE town ='Смоленск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE town ='Снежинск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='77', country_iso3='RUS' WHERE town ='Тверь' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='22', country_iso3='UKR' WHERE town ='Тернополь' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='75', country_iso3='RUS' WHERE town ='Томск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='76', country_iso3='RUS' WHERE town LIKE 'Тула%%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='UKR' WHERE town ='Харьков' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='UKR' WHERE town ='Чернигов' AND admin_code IS NULL;

UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE town LIKE 'Ялта%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='85', country_iso3='RUS' WHERE town LIKE 'Череповец%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE town LIKE 'челябинск%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE town LIKE 'Феодосия%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='08', country_iso3='RUS' WHERE town LIKE 'Уфа%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='KAZ' WHERE town LIKE 'Уральск%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='78', country_iso3='RUS' WHERE town LIKE 'Тюмень%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='75', country_iso3='RUS' WHERE town LIKE 'Томск%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='65', country_iso3='RUS' WHERE town LIKE 'Тольятти%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE town LIKE 'Судак%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='UKR' WHERE town LIKE 'Санкт-Петербур%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='UKR' WHERE town LIKE 'С - Пб%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='61', country_iso3='UKR' WHERE town LIKE 'РнД%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='UKR' WHERE town LIKE 'Петергоф%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='UKR' WHERE town = 'Петр' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='56', country_iso3='UKR' WHERE town = 'Орел' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='91', country_iso3='UKR' WHERE town = 'Норильск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='UKR' WHERE town = 'Н.Новгород' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town LIKE 'Москава%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town = 'Мск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE town = 'магнитогорск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='43', country_iso3='RUS' WHERE town = 'Липецк' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='91', country_iso3='RUS' WHERE town = 'Красноярск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='38', country_iso3='RUS' WHERE town = 'Краснодар' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='73', country_iso3='RUS' WHERE town LIKE 'Казань%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='20', country_iso3='RUS' WHERE town = 'Иркутск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='80', country_iso3='RUS' WHERE town = 'Ижевск' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='KAZ' WHERE town LIKE '%Уральск%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='UKR' WHERE town LIKE '%Нижний Новгород%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town LIKE '%Москва' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='33', country_iso3='RUS' WHERE town LIKE '%Вятка%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='84', country_iso3='RUS' WHERE town LIKE 'Волгоград%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE town LIKE 'Алушта%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE town LIKE 'Барнаул%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='84', country_iso3='RUS' WHERE town LIKE 'Volgograd%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE town LIKE 'Saint-Petersburg%';
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE town LIKE 'Saint-Petesburg%' ;
UPDATE geocacher SET admin_code='51', country_iso3='RUS' WHERE town LIKE '%Nizhniy Novgorod%' ;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town LIKE 'Mytishi%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town LIKE 'Moskva%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town = 'Korolev' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='25', country_iso3='RUS' WHERE town = 'Kaluga' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='52', country_iso3='RUS' WHERE town = 'Great Novgorod' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='31', country_iso3='RUS' WHERE town = 'Abakan' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='10', country_iso3='KAZ' WHERE town = 'Чимкент' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='05', country_iso3='ISR' WHERE town = 'Тель Авив' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='58', country_iso3='MDA' WHERE town = 'Тирасполь' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='GEO' WHERE town = 'Тбилиси' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE town = 'Уйское' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town = 'Сходня' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='UKR' WHERE town LIKE 'Стрельна%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='FIN' WHERE town = 'Руоколахти' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='ITA' WHERE town LIKE 'Рим%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='25', country_iso3='LVA' WHERE town LIKE 'Рига%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='52', country_iso3='CZE' WHERE town LIKE 'Прага%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='03', country_iso3='KAZ' WHERE town LIKE 'Нур-Султан%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='08', country_iso3='UKR' WHERE town LIKE 'Новая Каховка%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='10', country_iso3='CAN' WHERE town LIKE 'Монреаль%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='BLR' WHERE town LIKE 'Могилев%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='32', country_iso3='RUS' WHERE town LIKE 'Когалым%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='57', country_iso3='MDA' WHERE town LIKE 'Кишинев%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='ISR' WHERE town LIKE 'Иерусалим%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='05', country_iso3='UKR' WHERE town LIKE 'Донецкъ%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='18', country_iso3='UKR' WHERE town LIKE 'Диканька%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='38', country_iso3='RUS' WHERE town = 'Геленджик' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='60', country_iso3='MDA' WHERE town LIKE '%Бельцы%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='BLR' WHERE town LIKE 'Витебск%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='CAN' WHERE town LIKE 'Ванкувер%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='85', country_iso3='CZE' WHERE town LIKE 'Брно%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='16', country_iso3='DEU' WHERE town LIKE 'Берлин%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='25', country_iso3='LVA' WHERE town IN ('Riga', 'riga', 'Rīga') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='85', country_iso3='CZE' WHERE town LIKE 'Brno%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='86', country_iso3='POL' WHERE town LIKE 'Poznań%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='DEU' WHERE town LIKE 'Leverkusen%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='NLD' WHERE town LIKE 'Leiden%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='UKR' WHERE town IN ('Kyiv') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='UKR' WHERE town IN ('Kharkov') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='FIN' WHERE town = 'helsinki' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='DEU' WHERE town LIKE 'Duesseldorf%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='28', country_iso3='SWE' WHERE town LIKE 'Gothenburg%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='05', country_iso3='HUN' WHERE town LIKE 'Budapest%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='25', country_iso3='FIN' WHERE town = 'Порвоо' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='NLD' WHERE town LIKE 'Лейдсхендам%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE town = 'Кубинка' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE town LIKE 'Колпино%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='FIN' WHERE town in ('Вантаа', 'Vantaa') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='01', country_iso3='EST' WHERE town = 'Vasalemma' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='78', country_iso3='POL' WHERE town LIKE 'Жирардув%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='FIN' WHERE town in ('Rovaniemi') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='14', country_iso3='FIN' WHERE town in ('Puolanka') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='DEU' WHERE town LIKE 'Mettenheim%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='15', country_iso3='DEU' WHERE town LIKE 'Markvippach%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='VLG', country_iso3='BEL' WHERE town LIKE 'Affligem%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='63', country_iso3='LTU' WHERE town LIKE 'мажейкяй%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='19', country_iso3='LVA' WHERE town LIKE 'Лудза%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='17', country_iso3='LVA' WHERE town LIKE 'Лиепая%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='14', country_iso3='LVA' WHERE town LIKE 'Краслава%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='58', country_iso3='LTU' WHERE town LIKE 'Клайпеда%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='14', country_iso3='FIN' WHERE town in ('Каяни') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='LVA' WHERE town LIKE 'Даугавпилс%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='12', country_iso3='LVA' WHERE town LIKE 'Ozolnieki%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='LVA' WHERE town LIKE 'Jurmala%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='21', country_iso3='LVA' WHERE town LIKE 'Ciemupe%' AND admin_code IS NULL;


UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid=121300 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='83', country_iso3='RUS' WHERE uid=64874 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='83', country_iso3='RUS' WHERE uid=58813 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid=48649 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='82', country_iso3='RUS' WHERE uid=25817 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='82', country_iso3='RUS' WHERE uid=15957 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE uid = 8266 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='51', country_iso3='RUS' WHERE uid = 29360 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='44', country_iso3='AZE' WHERE uid = 141254 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='UKR' WHERE uid = 48429 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='38', country_iso3='RUS' WHERE uid = 80312 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE uid = 68157 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='14', country_iso3='UKR' WHERE uid = 38914 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE uid = 39489 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE uid=124479 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='53', country_iso3='RUS' WHERE uid=159290 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='59', country_iso3='RUS' WHERE uid=36762 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='59', country_iso3='RUS' WHERE uid=179580 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE uid=13844 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='UKR' WHERE uid = 4610 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid=22181 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='86', country_iso3='RUS' WHERE uid=142002 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='08', country_iso3='RUS' WHERE uid=3158 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='90', country_iso3='RUS' WHERE uid=39335 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='65', country_iso3='RUS' WHERE uid=37987 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='70', country_iso3='RUS' WHERE uid=128280 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid=138225 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE uid=13854 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE uid=16105 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='RUS' WHERE uid=19117 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid= 14748 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid in (163, 783, 1400, 2153) AND admin_code IS NULL; -- Moscow
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid= 1860 AND admin_code IS NULL; --  Moscow
UPDATE geocacher SET admin_code='07', country_iso3='UKR' WHERE uid = 2310 AND admin_code IS NULL;
UPDATE geocacher SET admin_code='34', country_iso3='RUS' WHERE uid= 27579 AND admin_code IS NULL; -- Komi
UPDATE geocacher SET admin_code='52', country_iso3='RUS' WHERE uid= 1700 AND admin_code IS NULL; -- Novgorod


UPDATE geocacher SET admin_code='02', country_iso3='BLR' WHERE oblast LIKE 'Гомельская обл%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='28', country_iso3='RUS' WHERE oblast='Karelia' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE oblast in ('Moscow', 'Moskow') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='UKR' WHERE oblast in ('А.Р.Крым','АР Крым') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='01', country_iso3='RUS' WHERE oblast='Адыгея респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='03', country_iso3='KAZ' WHERE oblast in ('Акмолинская', 'Акмолинская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='KAZ' WHERE oblast in ('Актюбинская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='01', country_iso3='KAZ' WHERE oblast in ('Алматинская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='04', country_iso3='RUS' WHERE oblast='Алтай респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='05', country_iso3='RUS' WHERE oblast in ('Амурская','Амурская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='RUS' WHERE oblast in ('архагельская') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='RUS' WHERE oblast in ('Астраханская обл.', 'Astrakhan') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='KAZ' WHERE oblast in ('Атырауская') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='01', country_iso3='BLR' WHERE oblast in ('Брестская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='RUS' WHERE oblast='Бурятия респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='BLR' WHERE oblast in ('Витебская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='84', country_iso3='RUS' WHERE oblast='волгоград' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='24', country_iso3='UKR' WHERE oblast in ('Волынская') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='15', country_iso3='KAZ' WHERE oblast in ('Восточно-Казахстанская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='53', country_iso3='RUS' WHERE oblast in ('г.Тогучин') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='03', country_iso3='BLR' WHERE oblast in ('Гродненская','Гродненская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='17', country_iso3='RUS' WHERE oblast='Дагестан респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='89', country_iso3='RUS' WHERE oblast='Еврейская авт. обл.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='71', country_iso3='RUS' WHERE oblast='Екатеринбург' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='27', country_iso3='UKR' WHERE oblast in ('Житомирская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='25', country_iso3='UKR' WHERE oblast in ('Закарпатская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='07', country_iso3='KAZ' WHERE oblast in ('Западно-Казахстанская обл.', 'Зап. Каз') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='26', country_iso3='UKR' WHERE oblast in ('Запорожская') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='UKR' WHERE oblast in ('Ивано Франковская', 'Ивано-Франковская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='21', country_iso3='RUS' WHERE oblast in ('Ивановская область') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='20', country_iso3='RUS' WHERE oblast='Иркутская область' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='22', country_iso3='RUS' WHERE oblast='Кабардино-Балкарская респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='24', country_iso3='RUS' WHERE oblast='Калмыкия - Хальмг Тангч респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='19', country_iso3='RUS' WHERE oblast='Ингушетия респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='92', country_iso3='RUS' WHERE oblast='Камчатский край' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='12', country_iso3='KAZ' WHERE oblast in ('Карагандинская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='27', country_iso3='RUS' WHERE oblast='Карачаево-Черкесская респ.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='28', country_iso3='RUS' WHERE oblast='Карелия' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='29', country_iso3='RUS' WHERE oblast in ('Кемеровская обл.','Кузбасс или Хакасия') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='UKR' WHERE oblast in ('Киев') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='28', country_iso3='RUS' WHERE oblast in ('Коми','Коми респ.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='KAZ' WHERE oblast in ('Костанайская', 'Костанайская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='38', country_iso3='RUS' WHERE oblast in ('краснодарский') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='14', country_iso3='KAZ' WHERE oblast in ('Кызылординская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE oblast in ('Ленинградская','Ленинградская Область') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='44', country_iso3='RUS' WHERE oblast in ('Магаданская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='06', country_iso3='BLR' WHERE oblast in ('Могилевская','Могилевская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='50', country_iso3='RUS' WHERE oblast in ('Ненецкий АО') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='16', country_iso3='UKR' WHERE oblast in ('Николаевская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='55', country_iso3='RUS' WHERE oblast in ('Оренбургская обл.','Тоцкое') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='11', country_iso3='KAZ' WHERE oblast in ('Павлодарская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='31', country_iso3='RUS' WHERE oblast in ('Республика Хакасия') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='19', country_iso3='UKR' WHERE oblast in ('Ровенская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='68', country_iso3='RUS' WHERE oblast in ('Северная Осетия респ.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='16', country_iso3='KAZ' WHERE oblast in ('Северо-Казахстанская','Северо-Казахстанская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='21', country_iso3='UKR' WHERE oblast in ('Сумская','Сумская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='22', country_iso3='UKR' WHERE oblast in ('Тернопольская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='75', country_iso3='RUS' WHERE oblast in ('Томская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='79', country_iso3='RUS' WHERE oblast in ('Тыва (Тува) респ.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='31', country_iso3='RUS' WHERE oblast in ('Хакасия респ.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='32', country_iso3='RUS' WHERE oblast in ('Ханты-Мансийский авт. окр.', 'Ханты-Мансийский Автономный округ - Югра АО.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='09', country_iso3='UKR' WHERE oblast in ('Хмельницкая обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='UKR' WHERE oblast in ('Черниговская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='03', country_iso3='UKR' WHERE oblast in ('Черновицкая обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='12', country_iso3='RUS' WHERE oblast in ('Чеченская респ.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='12', country_iso3='RUS' WHERE oblast in ('Читинская') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='15', country_iso3='RUS' WHERE oblast in ('Чукотский авт. окр.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='10', country_iso3='KAZ' WHERE oblast in ('Южно-Казахстанская обл.') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='63', country_iso3='RUS' WHERE oblast in ('Якутия') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='63', country_iso3='RUS' WHERE oblast in ('Ямало-Ненецкий авт. окр.','ЯНАО') AND admin_code IS NULL;

UPDATE geocacher SET admin_code='47', country_iso3='RUS' WHERE uid in (87, 18502, 1628) AND admin_code IS NULL; -- Moscow
UPDATE geocacher SET admin_code='42', country_iso3='RUS' WHERE uid in (8038, 845, 6136)
AND admin_code IS NULL;  -- Lenin

UPDATE geocacher SET admin_code='78', country_iso3='CZE' WHERE uid = 101481;
UPDATE geocacher SET admin_code='78', country_iso3='CZE' WHERE oblast LIKE 'Южная Моравия%' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='DEU' WHERE oblast in ('Бавария') AND admin_code IS NULL;
UPDATE geocacher SET admin_code='42', country_iso3='BGR' WHERE oblast = 'София' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='61', country_iso3='BGR' WHERE oblast = 'ВАРНА' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='39', country_iso3='BGR' WHERE oblast = 'Бургас' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='57', country_iso3='LTU' WHERE oblast = 'Каунасский уезд' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='58', country_iso3='LTU' WHERE oblast = 'Клайпедский уезд' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='65', country_iso3='LTU' WHERE oblast = 'Вильнюсский уезд' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='14', country_iso3='UZB' WHERE oblast = 'Ташкентский вилоят' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='UZB' WHERE oblast = 'Бухарский вилоят' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='KGZ' WHERE oblast = 'Чуйская обл.' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='92', country_iso3='MDA' WHERE oblast = 'Унгенский р-н' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='18', country_iso3='EST' WHERE oblast = 'Тартумаа' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='02', country_iso3='EST' WHERE oblast = 'Хийумаа' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='19', country_iso3='EST' WHERE oblast = 'Валгамаа' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='03', country_iso3='EST' WHERE oblast = 'Ида-Вирумаа' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='C1', country_iso3='FRA' WHERE oblast = 'Эльзас' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='13', country_iso3='DEU' WHERE oblast = 'Саксония' AND admin_code IS NULL;
UPDATE geocacher SET admin_code='08', country_iso3='EST' WHERE oblast = 'Ляэне-Вирумаа' AND admin_code IS NULL;

select distinct town  from geocacher where admin_code is null and  created_caches > 1 and found_caches > 1 order by town;
select count(*)  from geocacher where admin_code is null and  created_caches > 1 and found_caches > 1 ;

UPDATE geocacher SET admin_code='02', country_iso3='BLR' WHERE oblast in ('Gomel\\\'skaja','Гомельская', 'Гомельская обл.', 'Гомельская обл.', 'Гомельская обл.') AND admin_code IS NULL;

select distinct town  from geocacher where admin_code is null and  found_caches > 10 order by town;
select count(*)  from geocacher where admin_code is null and  (ifnull(created_caches,0)+ifnull(found_caches,0)) > 10 ;

select pid, nickname, country, town, oblast, country_iso3, created_caches, found_caches, last_login, (ifnull(created_caches,0)+ifnull(found_caches,0)) as cnt
from geocacher where admin_code is null and  (ifnull(created_caches,0)+ifnull(found_caches,0)) > 10
order by cnt desc;

