UPDATE geocacher SET country_iso3='ALB' WHERE country='Albania';
UPDATE geocacher SET country_iso3='DZA' WHERE country='Algeria';
UPDATE geocacher SET country_iso3='AND' WHERE country='Andorra';
UPDATE geocacher SET country_iso3='AGO' WHERE country='Angola';
UPDATE geocacher SET country_iso3='ARG' WHERE country='Argentina';
UPDATE geocacher SET country_iso3='ARM' WHERE country='Armenia';
UPDATE geocacher SET country_iso3='AUT' WHERE country='Austria';
UPDATE geocacher SET country_iso3='AUT' WHERE country='Awstria';
UPDATE geocacher SET country_iso3='AZE' WHERE country='Azerbaijan';
UPDATE geocacher SET country_iso3='BHR' WHERE country='Bahrain';
UPDATE geocacher SET country_iso3='BRB' WHERE country='Barbados';
UPDATE geocacher SET country_iso3='BLR' WHERE country='Belarus';
UPDATE geocacher SET country_iso3='BEL' WHERE country='belgie';
UPDATE geocacher SET country_iso3='BLZ' WHERE country='Belize';
UPDATE geocacher SET country_iso3='BMU' WHERE country='Bermuda';
UPDATE geocacher SET country_iso3='BOL' WHERE country='Bolivia';
UPDATE geocacher SET country_iso3='BGR' WHERE country in ('Bulgaria', 'ВАРНА');
UPDATE geocacher SET country_iso3='CAN' WHERE country='CA';
UPDATE geocacher SET country_iso3='KHM' WHERE country='Cambodia';
UPDATE geocacher SET country_iso3='CAN' WHERE country='Canada';
UPDATE geocacher SET country_iso3='CPV' WHERE country='Cape Verde';
UPDATE geocacher SET country_iso3='SUN' WHERE country='CCCP';
UPDATE geocacher SET country_iso3='CZE' WHERE country='Ceskaja respublika';
UPDATE geocacher SET country_iso3='CHN' WHERE country='China';
UPDATE geocacher SET country_iso3='CHN' WHERE country='Cina';
UPDATE geocacher SET country_iso3='COL' WHERE country='Colombia';
UPDATE geocacher SET country_iso3='COG' WHERE country='Congo';
UPDATE geocacher SET country_iso3='CRI' WHERE country='Costa Rica';
UPDATE geocacher SET country_iso3='HRV' WHERE country='Croatia';
UPDATE geocacher SET country_iso3='CYP' WHERE country='Cyprus';
UPDATE geocacher SET country_iso3='CZE' WHERE country='czech';
UPDATE geocacher SET country_iso3='CZE' WHERE country='czech rep';
UPDATE geocacher SET country_iso3='CZE' WHERE country='Czech Repbulic';
UPDATE geocacher SET country_iso3='CZE' WHERE country='Czech Republic';
UPDATE geocacher SET country_iso3='CZE' WHERE country='Czechija';
UPDATE geocacher SET country_iso3='DNK' WHERE country='Denmark';
UPDATE geocacher SET country_iso3='DEU' WHERE country='Deutschland';
UPDATE geocacher SET country_iso3='DOM' WHERE country='Dominican Republic';
UPDATE geocacher SET country_iso3='EGY' WHERE country='Egypt';
UPDATE geocacher SET country_iso3='GBR' WHERE country='England';
UPDATE geocacher SET country_iso3='EST' WHERE country='Estonia';
UPDATE geocacher SET country_iso3='ETH' WHERE country='Ethiopia';
UPDATE geocacher SET country_iso3='FIN' WHERE country='Finland';
UPDATE geocacher SET country_iso3='FRA' WHERE country='France';
UPDATE geocacher SET country_iso3='FRA' WHERE country in ('Francia', 'Франция');
UPDATE geocacher SET country_iso3='GBR' WHERE country in ('GB', 'uk');
UPDATE geocacher SET country_iso3='GEO' WHERE country='Georgia';
UPDATE geocacher SET country_iso3='DEU' WHERE country='Germania';
UPDATE geocacher SET country_iso3='DEU' WHERE country='Germany';
UPDATE geocacher SET country_iso3='GHA' WHERE country='Ghana';
UPDATE geocacher SET country_iso3='GIB' WHERE country='Gibraltar';
UPDATE geocacher SET country_iso3='GBR' WHERE country='Great Britain';
UPDATE geocacher SET country_iso3='GRC' WHERE country='Greece';
UPDATE geocacher SET country_iso3='GRL' WHERE country='Greenland';
UPDATE geocacher SET country_iso3='GTM' WHERE country='Guatemala';
UPDATE geocacher SET country_iso3='GUY' WHERE country='Guyana';
UPDATE geocacher SET country_iso3='HTI' WHERE country='Haiti';
UPDATE geocacher SET country_iso3='HND' WHERE country='Honduras';
UPDATE geocacher SET country_iso3='HUN' WHERE country='Hungary';
UPDATE geocacher SET country_iso3='IRL' WHERE country='irland';
UPDATE geocacher SET country_iso3='ITA' WHERE country='Italia';
UPDATE geocacher SET country_iso3='ITA' WHERE country='Italy';
UPDATE geocacher SET country_iso3='KWT' WHERE country='Kuwait';
UPDATE geocacher SET country_iso3='LVA' WHERE country='Latvija';
UPDATE geocacher SET country_iso3='LUX' WHERE country='Luxembourg';
UPDATE geocacher SET country_iso3='MWI' WHERE country='Malawi';
UPDATE geocacher SET country_iso3='MLI' WHERE country='Mali';
UPDATE geocacher SET country_iso3='MAR' WHERE country='Marocco';
UPDATE geocacher SET country_iso3='NAM' WHERE country='Namibia';
UPDATE geocacher SET country_iso3='NLD' WHERE country='Netherlands';
UPDATE geocacher SET country_iso3='NPL' WHERE country='Nepal';
UPDATE geocacher SET country_iso3='NZL' WHERE country='New Zealand';
UPDATE geocacher SET country_iso3='NFK' WHERE country='Norfolk Island';
UPDATE geocacher SET country_iso3='PAK' WHERE country='Pakistan';
UPDATE geocacher SET country_iso3='PER' WHERE country='Peru';
UPDATE geocacher SET country_iso3='POL' WHERE country='Poland';
UPDATE geocacher SET country_iso3='POL' WHERE country='Polsha';
UPDATE geocacher SET country_iso3='POL' WHERE country='Polska';
UPDATE geocacher SET country_iso3='PRI' WHERE country='Puerto Rico';
UPDATE geocacher SET country_iso3='QAT' WHERE country='Qatar';
UPDATE geocacher SET country_iso3='ROU' WHERE country='Romania';
UPDATE geocacher SET country_iso3='RUS' WHERE country='RU';
UPDATE geocacher SET country_iso3='ROU' WHERE country='rumania';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Russia';
UPDATE geocacher SET country_iso3='RUS' WHERE country='RussianFederation';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Russian Federation';
UPDATE geocacher SET country_iso3='SLE' WHERE country='Sierra Leone';
UPDATE geocacher SET country_iso3='SVK' WHERE country='Slovakia';
UPDATE geocacher SET country_iso3='SOM' WHERE country='Somalia';
UPDATE geocacher SET country_iso3='FIN' WHERE country='Suomi - Finland';
UPDATE geocacher SET country_iso3='SWE' WHERE country='Svezia';
UPDATE geocacher SET country_iso3='SWE' WHERE country='Sweden';
UPDATE geocacher SET country_iso3='SYR' WHERE country='Syria';
UPDATE geocacher SET country_iso3='TJK' WHERE country='Tajikistan';
UPDATE geocacher SET country_iso3='TZA' WHERE country='Tanzania';
UPDATE geocacher SET country_iso3='THA' WHERE country='Thailand';
UPDATE geocacher SET country_iso3='BHS' WHERE country='The Bahamas';
UPDATE geocacher SET country_iso3='TUN' WHERE country='Tunisia';
UPDATE geocacher SET country_iso3='UKR' WHERE country='UA';
UPDATE geocacher SET country_iso3='UGA' WHERE country='Uganda';
UPDATE geocacher SET country_iso3='UKR' WHERE country='Ukraine';
UPDATE geocacher SET country_iso3='GBR' WHERE country='United Kingdom';
UPDATE geocacher SET country_iso3='USA' WHERE country='United States';
UPDATE geocacher SET country_iso3='URY' WHERE country='Uruguay';
UPDATE geocacher SET country_iso3='USA' WHERE country='US';
UPDATE geocacher SET country_iso3='USA' WHERE country='USA';
UPDATE geocacher SET country_iso3='UZB' WHERE country='Uzbekistan';
UPDATE geocacher SET country_iso3='VNM' WHERE country='VietNam';
UPDATE geocacher SET country_iso3='VNM' WHERE country='Viet Nam';
UPDATE geocacher SET country_iso3='SRB' WHERE country='Yugoslavia';
UPDATE geocacher SET country_iso3='AUT' WHERE country='Австрия';
UPDATE geocacher SET country_iso3='AZE' WHERE country='Азербайджан';
UPDATE geocacher SET country_iso3='ARM' WHERE country='Армения';
UPDATE geocacher SET country_iso3='BLR' WHERE country='Беларусь';
UPDATE geocacher SET country_iso3='BGR' WHERE country='Болгария';
UPDATE geocacher SET country_iso3='BGR' WHERE country='България';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Воможно Россия';
UPDATE geocacher SET country_iso3='DEU' WHERE country='Германия';
UPDATE geocacher SET country_iso3='NLD' WHERE country='Голландия';
UPDATE geocacher SET country_iso3='HND' WHERE country='Гондурас';
UPDATE geocacher SET country_iso3='GEO' WHERE country='Грузия';
UPDATE geocacher SET country_iso3='DNK' WHERE country='Дания';
UPDATE geocacher SET country_iso3='ISR' WHERE country in ('Израиль', 'Israel');
UPDATE geocacher SET country_iso3='ESP' WHERE country='Испания';
UPDATE geocacher SET country_iso3='ITA' WHERE country='Италия';
UPDATE geocacher SET country_iso3='KAZ' WHERE country='Казахстан';
UPDATE geocacher SET country_iso3='CAN' WHERE country='Канада';
UPDATE geocacher SET country_iso3='KGZ' WHERE country='Киргизия';
UPDATE geocacher SET country_iso3='LVA' WHERE country='Латвия';
UPDATE geocacher SET country_iso3='LTU' WHERE country='Литва';
UPDATE geocacher SET country_iso3='LTU' WHERE country='Литва / Крым';
UPDATE geocacher SET country_iso3='MDA' WHERE country='Молдова';
UPDATE geocacher SET country_iso3='POL' WHERE country='Польша';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Росия';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Россиия';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Россия';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Москва';
UPDATE geocacher SET country_iso3='RUS' WHERE country in ('Россия~', 'ДНР');
UPDATE geocacher SET country_iso3='RUS' WHERE country='Россия~no';
UPDATE geocacher SET country_iso3='RUS' WHERE country='Россия~нет';
UPDATE geocacher SET country_iso3='RUS' WHERE country='РФ';
UPDATE geocacher SET country_iso3='SUN' WHERE country in ('Советский Союз', 'СССР');
UPDATE geocacher SET country_iso3='SVN' WHERE country='Словения';
UPDATE geocacher SET country_iso3='TJK' WHERE country='Таджикистан';
UPDATE geocacher SET country_iso3='TKM' WHERE country='Туркмения';
UPDATE geocacher SET country_iso3='UZB' WHERE country='Узбекистан';
UPDATE geocacher SET country_iso3='UKR' WHERE country='Украина';
UPDATE geocacher SET country_iso3='FIN' WHERE country='Финляндия';
UPDATE geocacher SET country_iso3='CZE' WHERE country='Чехия';
UPDATE geocacher SET country_iso3='CZE' WHERE country IN ('Чешская республика', 'Ceska republika');
UPDATE geocacher SET country_iso3='EST' WHERE country='Эстония';
UPDATE geocacher SET country_iso3='ETH' WHERE country='эфиопия';

UPDATE geocacher SET country_iso3='RUS', country='Россия' where uid IN (1860, 2153, 37, 21, 42,  783, 1700, 50, 1400, 6136, 37987, 22181, 31, 51, 52, 82, 84, 96, 100, 111, 129, 149)  AND country_iso3 IS NULL;
UPDATE geocacher SET country_iso3='RUS', country='Россия' where uid IN (158, 159, 173, 191, 197, 219, 227, 230, 261, 290, 325, 328, 335, 352, 359, 410, 456, 488, 499, 505, 552, 571)  AND country_iso3 IS NULL;
UPDATE geocacher SET country_iso3='RUS', country='Россия' where uid IN (542, 544, 553, 559, 562, 566, 572, 575)  AND country_iso3 IS NULL;
UPDATE geocacher SET country_iso3='RUS', country='Россия' where uid IN (576, 577, 578, 589, 597, 598, 609, 614, 616, 621, 623, 646, 647, 659, 1970, 3239, 4855, 50338)  AND country_iso3 IS NULL;
UPDATE geocacher SET country_iso3='UKR', country='Украина' where uid IN (2310, 4610) AND country_iso3 IS NULL;
UPDATE geocacher SET country_iso3='FIN', country='Финляндия' where uid IN (27088, 123717)  AND country_iso3 IS NULL;
select id, uid, nickname, country, created_caches, found_caches, photo_albums, last_login from geocacher where country_iso3 is null and created_caches > 1 and found_caches > 1;

