# Generated by Django 3.1.2 on 2020-11-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cach',
            name='created_by',
            field=models.IntegerField(db_column='created_by_uid', default=0),
        ),
    ]
