# Generated by Django 3.1.2 on 2020-11-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0002_auto_20201103_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cach',
            old_name='loc_EW_minute',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='cach',
            old_name='loc_NS_minute',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='loc_EW',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='loc_EW_degree',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='loc_NS',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='loc_NS_degree',
        ),
    ]
