# Generated by Django 3.1.2 on 2020-11-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0003_auto_20201103_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cach',
            name='cach_attr',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='cach_class',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='cach_type',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='coauthors',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='created_by',
        ),
    ]
