# Generated by Django 3.1.2 on 2020-11-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0004_auto_20201103_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cach',
            name='changed_date',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='code_fips10_4',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='code_iso3166_2',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='dostupnost',
        ),
        migrations.RemoveField(
            model_name='cach',
            name='mestnost',
        ),
        migrations.RemoveField(
            model_name='geocacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='geocacher',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='geocacher',
            name='icq',
        ),
        migrations.RemoveField(
            model_name='geocacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='geocacher',
            name='photo_albums',
        ),
        migrations.RemoveField(
            model_name='geocacher',
            name='web',
        ),
    ]
