# Generated by Django 3.1.2 on 2020-11-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0005_auto_20201103_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcreatecach',
            name='updated',
        ),
    ]
