# Generated by Django 3.1.2 on 2020-11-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0006_remove_logcreatecach_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logseekcach',
            name='updated',
        ),
    ]
