# Generated by Django 3.1.2 on 2020-11-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0007_remove_logseekcach_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecommendcach',
            name='updated',
        ),
    ]
