# Generated by Django 3.1.2 on 2020-11-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0008_remove_logrecommendcach_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogPhotoAlbum',
        ),
    ]
