# Generated by Django 3.1.2 on 2020-11-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0009_delete_logphotoalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cach',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GeoCachSU.geocacher'),
        ),
    ]
