# Generated by Django 3.1.2 on 2020-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0010_cach_author'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geocacher',
            index=models.Index(fields=['uid'], name='geocacher_uid_4f8b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='geocacher',
            index=models.Index(fields=['nickname'], name='geocacher_nicknam_9048e5_idx'),
        ),
    ]
