# Generated by Django 3.1.2 on 2020-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCachSU', '0011_auto_20201110_1322'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cach',
            index=models.Index(fields=['pid'], name='cach_pid_64a462_idx'),
        ),
        migrations.AddIndex(
            model_name='cach',
            index=models.Index(fields=['type_code'], name='cach_type_co_d9d356_idx'),
        ),
        migrations.AddIndex(
            model_name='cach',
            index=models.Index(fields=['created_date'], name='cach_created_c1458c_idx'),
        ),
        migrations.AddIndex(
            model_name='cach',
            index=models.Index(fields=['country_code'], name='cach_country_fe35df_idx'),
        ),
        migrations.AddIndex(
            model_name='cach',
            index=models.Index(fields=['admin_code'], name='cach_admin_c_8a7d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedescription',
            index=models.Index(fields=['cache_pid'], name='cache_descr_cache_p_f5e8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cachelog',
            index=models.Index(fields=['logged_by_uid'], name='cache_log_logged__bb4006_idx'),
        ),
        migrations.AddIndex(
            model_name='cachelog',
            index=models.Index(fields=['cache_pid'], name='cache_log_cache_p_1daf69_idx'),
        ),
        migrations.AddIndex(
            model_name='cachelog',
            index=models.Index(fields=['log_type'], name='cache_log_log_typ_3889a2_idx'),
        ),
        migrations.AddIndex(
            model_name='cachelog',
            index=models.Index(fields=['log_date'], name='cache_log_log_dat_fca718_idx'),
        ),
        migrations.AddIndex(
            model_name='cachstat',
            index=models.Index(fields=['cach_pid'], name='cach_stat_cach_pi_ce55a6_idx'),
        ),
        migrations.AddIndex(
            model_name='geocachersearchstat',
            index=models.Index(fields=['geocacher_uid'], name='geocacher_s_geocach_96ef12_idx'),
        ),
        migrations.AddIndex(
            model_name='geocacherstat',
            index=models.Index(fields=['uid'], name='geocacher_s_uid_c31f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='logcreatecach',
            index=models.Index(fields=['author_uid'], name='log_create__author__cbf843_idx'),
        ),
        migrations.AddIndex(
            model_name='logcreatecach',
            index=models.Index(fields=['cach_pid'], name='log_create__cach_pi_df4329_idx'),
        ),
        migrations.AddIndex(
            model_name='logcreatecach',
            index=models.Index(fields=['created_date'], name='log_create__created_21dd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='logrecommendcach',
            index=models.Index(fields=['cacher_uid'], name='log_recomme_cacher__f67ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='logrecommendcach',
            index=models.Index(fields=['cach_pid'], name='log_recomme_cach_pi_9b935c_idx'),
        ),
        migrations.AddIndex(
            model_name='logseekcach',
            index=models.Index(fields=['cacher_uid'], name='log_seek_ca_cacher__740b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='logseekcach',
            index=models.Index(fields=['cach_pid'], name='log_seek_ca_cach_pi_b3269f_idx'),
        ),
        migrations.AddIndex(
            model_name='logseekcach',
            index=models.Index(fields=['found_date'], name='log_seek_ca_found_d_68b594_idx'),
        ),
    ]
