from django.urls import path
from django.views.decorators.cache import cache_page
from gpsfun.geocaching_su_stat.views import geocaching_su_geocacher_stat_countries
from gpsfun.geocaching_su_stat.views import (
    cach_rate_by_index, cach_rate_by_found, cach_rate_by_recommend,
    cach_view, geocacher_view, geocaching_su, geocaching_su_cach_stat,
    geocaching_su_cache_statistics, geocaching_su_geocacher_stat,
    geocaching_su_geocacher_stat_countries,
    geocaching_su_personal_statistics,
    geocaching_su_personal_charts, gcsu_found_my_caches_stat,
    gcsu_i_found_caches_stat, gcsu_regions_found_caches_stat,
    geocaching_su_chart, cache_info, change_country, region_caches,
    geocaching_su_cach_stat_pie,
    geocaching_su_personal_found_cache_pie,
    geocaching_su_personal_created_cache_pie,
    gcsu_personal_found_current_chart,
    geocaching_su_cach_stat_chart,
    geocaching_su_cach_pertype_stat_chart,
    geocaching_su_cache_per_type_chart,
    geocaching_su_geocacher_stat_chart,
    geocaching_su_geocacher_activity_chart,
    geocaching_su_geocacher_activity_creating_chart,
    geocaching_su_geocacher_stat_pie,
    # geocaching_su_geocacher_stat_pie,
    geocacher_activity, geocacher_rate, geocacher_rate,
    geocacher_rate_unreal, geocacher_rate_real,
    geocacher_rate_current, geocacher_rate_unreal_current,
    geocacher_rate_real_current, geocacher_rate_last,
    geocacher_rate_unreal_last, geocacher_search_rating_current,
    geocacher_rate_real_last, geocacher_search_rating,
    coordinate_converter, ajax_converter, filter_change_subjects,
    cach_rate_by_index, cach_rate_by_found,
    cach_rate_by_recommend, cach_view, geocaching_su_profile,
)

urlpatterns = [
    path('cache/rate/index/',
        cach_rate_by_index, name="cach-rate-by-index"),
    path('cache/rate/found/',
        cach_rate_by_found, name="cach-rate-by-found"),
    path('cache/rate/recommend/', cach_rate_by_recommend,
        name="cach-rate-by-recommend"),
    path('cache/view/<int:cach_pid>/',
        cach_view, name="geocaching-su-cach-view"),
    path('geocacher/view/<int:geocacher_uid>/',
        geocacher_view, name="geocaching-su-geocacher-view"),
    path('', geocaching_su, name="geocaching-su"),
    path('cache/stat/', geocaching_su_cach_stat,
        name="geocaching-su-cach-stat"),
    path('cache/statistics/', geocaching_su_cache_statistics,
        name="geocaching-su-cache-statistics"),
    path('geocacher/stat/', geocaching_su_geocacher_stat,
        name="geocaching-su-geocacher-stat"),
    path('geocacher/stat/countries/', cache_page(60 * 60 * 8)
        (geocaching_su_geocacher_stat_countries), name="geocaching-su-geocacher-stat-countries"),
    path('geocacher/personal/statistics/',
        geocaching_su_personal_statistics,
        name="geocaching-su-personal-stat"),
    path('geocacher/personal/charts/',
        geocaching_su_personal_charts,
        name="geocaching-su-personal-charts"),
    path('geocacher/found/my/caches/',
        gcsu_found_my_caches_stat, name="found-my-caches-stat"),
    path('geocacher/i/found/caches/',
        gcsu_i_found_caches_stat, name="i-found-caches-stat"),
    path('geocacher/regions/found/caches/',
        gcsu_regions_found_caches_stat,
        name="regions-found-caches-stat"),
    path('chart/', geocaching_su_chart,
        name="geocaching-su-chart"),
    path('cache/info/', cache_info, name="cache-info"),
    path('change/country/', change_country,
        name="change-country"),
    path('region/caches/', region_caches,
        name="region-caches"),
    path('cache/stat/pie/', geocaching_su_cach_stat_pie,
        name="geocaching-su-cach-stat-pie"),
    path('personal/found/pie/<int:geocacher_uid>/',
        geocaching_su_personal_found_cache_pie,
        name="gcsu-personal-found-cache-pie"),
    path('personal/created/pie/<int:geocacher_uid>/',
        geocaching_su_personal_created_cache_pie,
        name="gcsu-personal-created-cache-pie"),
    path('personal/found/current/chart/',
        gcsu_personal_found_current_chart,
        name="gcsu-personal-found-current-chart"),
    path('cache/stat/chart/',
        geocaching_su_cach_stat_chart,
        name="geocaching-su-cach-stat-chart"),
    path('cache/types/stat/chart/',
        geocaching_su_cach_pertype_stat_chart,
        name="geocaching-su-cach-pertype-stat-chart"),
    path('cache/all/types/stat/chart/',
        geocaching_su_cache_per_type_chart,
        name="geocaching-su-cache-per-type-chart"),
    path('geocacher/stat/chart/',
        geocaching_su_geocacher_stat_chart,
        name="geocaching-su-geocacher-stat-chart"),
    path('geocacher/activity/chart/',
        geocaching_su_geocacher_activity_chart,
        name="geocaching-su-geocacher-activity-chart"),
    path('geocacher/activity/creating/chart/',
        geocaching_su_geocacher_activity_creating_chart,
        name="geocaching-su-geocacher-activity-creating-chart"),
    path('geocacher/stat/pie/<only_active>/',
        geocaching_su_geocacher_stat_pie,
        name="geocaching-su-activegeocacher-stat-pie"),
    path('geocacher/stat/pie/',
        geocaching_su_geocacher_stat_pie,
        name="geocaching-su-geocacher-stat-pie"),
    path('geocacher/activity/',
        geocacher_activity, name="geocacher-activity"),
    path('geocacher/list/', geocacher_rate,
        name="geocacher-rate"),
    path('geocacher/list/all/',
        geocacher_rate, name="geocacher-rate-all"),
    path('geocacher/list/vi/',
        geocacher_rate_unreal, name="geocacher-rate-vi"),
    path('geocacher/list/tr/',
        geocacher_rate_real, name="geocacher-rate-tr"),
    path('geocacher/list/all/current/',
        geocacher_rate_current, name="geocacher-rate-all-curr"),
    path('geocacher/list/vi/current/',
        geocacher_rate_unreal_current,
        name="geocacher-rate-vi-curr"),
    path('geocacher/list/tr/current/',
        geocacher_rate_real_current,
        name="geocacher-rate-tr-curr"),
    path('geocacher/list/all/last/', geocacher_rate_last,
        name="geocacher-rate-all-last"),
    path('geocacher/list/vi/last/',
        geocacher_rate_unreal_last,
        name="geocacher-rate-vi-last"),
    path('geocacher/list/tr/last/',
        geocacher_rate_real_last,
        name="geocacher-rate-tr-last"),
    path('geocacher/search/rating/current/',
        geocacher_search_rating_current,
        name="geocacher-search-rating-current"),
    path('geocacher/search/rating/',
        geocacher_search_rating,
        name="geocacher-search-rating"),
    path('calculator/',
        coordinate_converter,
        name="coordinate-converter"),
    path('converter/', ajax_converter,
        name="ajax-converter"),
    path('change/subjects/', filter_change_subjects,
        name="filter-change-subjects"),
    path('gcsu/profile/<nickname>/', geocaching_su_profile,
        name="gcsu-profile"),
]

