# Generated by Django 3.1.2 on 2021-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geonameid', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('asciiname', models.CharField(blank=True, max_length=200, null=True)),
                ('alternatenames', models.CharField(blank=True, max_length=4000, null=True)),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longitude', models.FloatField(default=0, null=True)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
                ('fcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(db_index=True, max_length=2, null=True)),
                ('cc2', models.CharField(blank=True, max_length=60, null=True)),
                ('admin1', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('admin2', models.CharField(blank=True, max_length=80, null=True)),
                ('admin3', models.CharField(blank=True, max_length=20, null=True)),
                ('admin4', models.CharField(blank=True, max_length=20, null=True)),
                ('population', models.IntegerField(null=True)),
                ('elevation', models.IntegerField(null=True)),
                ('gtopo30', models.IntegerField(null=True)),
                ('timezone', models.CharField(blank=True, max_length=40, null=True)),
                ('moddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geo_city',
            },
        ),
        migrations.CreateModel(
            name='GeoCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(db_index=True, default=0)),
                ('iso', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('capital', models.CharField(blank=True, max_length=128, null=True)),
                ('iso3', models.CharField(db_index=True, max_length=3)),
                ('iso_num', models.IntegerField(db_index=True)),
                ('fips', models.CharField(blank=True, max_length=2, null=True)),
                ('area_sqkm', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('continent', models.CharField(max_length=2)),
                ('tld', models.CharField(blank=True, max_length=6, null=True)),
                ('currency_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'geo_country',
            },
        ),
        migrations.CreateModel(
            name='GeoCountryAdminSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(db_index=True, default=0)),
                ('country_iso', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'db_table': 'geo_country_subject',
            },
        ),
        migrations.CreateModel(
            name='GeoCountryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso3', models.CharField(db_index=True, max_length=3)),
                ('lang_code', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'db_table': 'geo_country_language',
            },
        ),
        migrations.CreateModel(
            name='GeoCountryNeighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso3', models.CharField(db_index=True, max_length=3)),
                ('neighbour_iso', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'db_table': 'geo_country_neighbour',
            },
        ),
        migrations.CreateModel(
            name='GeoRUSSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(default=0)),
                ('country_iso', models.CharField(max_length=2)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(max_length=10)),
                ('ascii_name', models.CharField(blank=True, max_length=128, null=True)),
                ('iso_3166_2_code', models.CharField(max_length=16)),
                ('gai_code', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'geo_russia_subject',
            },
        ),
        migrations.CreateModel(
            name='GeoUKRSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField(default=0)),
                ('country_iso', models.CharField(max_length=2)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(max_length=10)),
                ('ascii_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'geo_ukraine_subject',
            },
        ),
    ]
