# Generated by Django 3.1.2 on 2021-06-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.FilePathField(match='skin.*\\.css', path='/mnt/code/kostin/dev/GPSFUN/gpsfun/htdocs/gpsfun-admin/')),
                ('rows_per_page', models.IntegerField(default=15)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'adminprefs',
            },
        ),
    ]
