# Generated by Django 3.1.2 on 2020-11-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCheckData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocacher_count', models.IntegerField(blank=True, null=True)),
                ('geocacher_wo_country_count', models.IntegerField(blank=True, null=True)),
                ('geocacher_wo_region_count', models.IntegerField(blank=True, null=True)),
                ('cache_count', models.IntegerField(blank=True, null=True)),
                ('cache_wo_country_count', models.IntegerField(blank=True, null=True)),
                ('cache_wo_region_count', models.IntegerField(blank=True, null=True)),
                ('cache_wo_author_count', models.IntegerField(blank=True, null=True)),
                ('checking_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_check_data',
            },
        ),
    ]
