# Generated by Django 3.1.2 on 2021-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridge',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
