# Generated by Django 3.1.2 on 2021-04-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0002_auto_20210426_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carpathians.geopoint', verbose_name='point')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Carpathians.route', verbose_name='route')),
            ],
            options={
                'verbose_name': 'route point',
                'verbose_name_plural': 'route points',
                'db_table': 'route_point',
            },
        ),
    ]
