# Generated by Django 3.1.2 on 2021-04-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0003_routepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
