# Generated by Django 3.1.2 on 2021-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0005_auto_20210427_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
