# Generated by Django 3.1.2 on 2021-04-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0006_route_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak',
            name='map_image',
        ),
        migrations.AddField(
            model_name='peak',
            name='descent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routesection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
