# Generated by Django 3.1.2 on 2021-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0007_auto_20210428_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peak',
            name='descent',
        ),
        migrations.AddField(
            model_name='route',
            name='descent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
