# Generated by Django 3.1.2 on 2021-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0009_auto_20210428_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
