# Generated by Django 3.1.2 on 2021-04-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0010_route_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='max_difficulty',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
