# Generated by Django 3.1.2 on 2021-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0011_auto_20210430_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridge',
            name='map_image',
        ),
    ]
