# Generated by Django 3.1.2 on 2021-04-30 10:46

from django.db import migrations, models
import gpsfun.utils


class Migration(migrations.Migration):

    dependencies = [
        ('Carpathians', '0012_remove_ridge_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to=gpsfun.utils.get_image_path, verbose_name='map'),
        ),
    ]
