# Generated by Django 3.1.2 on 2021-06-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('cache_url', models.CharField(blank=True, max_length=128, null=True)),
                ('url_by_code', models.BooleanField(default=False)),
                ('enabled', models.BooleanField()),
                ('logo', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'geosite',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NS_degree', models.FloatField(blank=True, null=True)),
                ('EW_degree', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Geothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=32)),
                ('type_code', models.CharField(max_length=2)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('cach_type', models.CharField(blank=True, max_length=128, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('admin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('country_name', models.CharField(blank=True, max_length=64, null=True)),
                ('oblast_name', models.CharField(blank=True, max_length=128, null=True)),
                ('oblast', models.CharField(blank=True, max_length=64, null=True)),
                ('geosite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoMap.geosite')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoMap.location')),
            ],
            options={
                'db_table': 'geothing',
            },
        ),
        migrations.CreateModel(
            name='BlockNeedBeDivided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField()),
                ('bb', models.CharField(max_length=128)),
                ('idx', models.IntegerField()),
                ('geosite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoMap.geosite')),
            ],
            options={
                'db_table': 'block_need_be_divided',
            },
        ),
    ]
